### ISSUE TITLE
Create a CLI for fluffy (based on NX)

### ISSUE THREAD

**Issue by shairez** [qwikifiers/qwik-ui#431]
This will be based on something similar to the work @dmitry-stepanenko have done with Angular qwikify

**Comment by EmanueleGurini** [comment]
Hello, I would like to work on this issue, can I grab it?

**Comment by shairez** [comment]
Yes! Thanks!

Let's just sync first, I want to make sure you get all the context

Please DM me on Discord

**Comment by dmitry-stepanenko** [comment]
A couple of notes:
- in order to leverage nx capabilities it's mostly enough to install `nx` package and add `"nx": { "targets": {} }` to the package.json (basically what `npx nx@latest init` does if you opt out everything it asks). It might be nice to also keep `nx.json` but it is not necessary. Might be reasonable to keep nx's init steps in your CLI though
- You can then reference the project by the `name` value from `project.json` like `nx run my-qwik-basic-starter:build` in your generators
- In the angular integration installing nx and qwik-nx was a one-time thingy, here I guess it makes much more sense to just keep `nx` as a peer dependency of the cli package (oh and make sure it works well with pnpm, I had a few problems there)
- Nx has a ton of utils to work with when creating generators, but for the CLI layer it will be needed to code it out manually. You can still rely on existing solutions from [nx](https://github.com/nrwl/nx/tree/master/packages/nx/src/command-line) or [qwik-nx](https://github.com/qwikifiers/qwik-nx/blob/main/packages/create-qwik-nx/bin/create-qwik-nx.ts) repos if you need inspiration
- In order to add generators for the package, use a generator for generators [@nx/plugin:generator](https://nx.dev/nx-api/plugin/generators/generator) (xzibit vibes with a TV here). If there're any questions on how to actually write one, feel free to reach out to Shai or me in the discord
