### ISSUE TITLE
Finalize the new popover component

### ISSUE THREAD

**Issue by shairez** [qwikifiers/qwik-ui#471]

**Comment by wmertens** [comment]
General idea is to avoid running code on supported browsers.

This is the required code on supported browsers:
- the anchor code, which probably needs to run before onToggle, so in a visibleTask (right @thejackshelton?)
- if we want to allow binding to a signal for popout status, we'll need to set it in onToggle$

On unsupported browsers:
- the polyfill needs to load before users can interact with the trigger, so in visibletask or even at load
- before the popover item is made visible, we need to rerender the popover and move it to the bottom of `<body>` so the anchor function can correctly calculate its offsets
- signal bind would also need onToggle

The polyfill can be loaded by a `<PopoverPolyfill />` component that renders a div + some css to keep it hidden when the browser supports popover. Then the load can happen in useVisibleTask, and the polyfill component should be put somewhere at the top of the page.

Things to investigate:
- can we double-hide popover elements so that on first toggle we can load the anchor code/do the rerender?
- do we want to ask the user to render a `<PopoverPolyfill />` div or do we render it ourselves, taking away the decision? But then it might be at the bottom of the page and the polyfill doesn't load in time for the user clicking on it
- do we want to handle things in the trigger component ourselves, allowing running things before the popover fires?

**Comment by wmertens** [comment]
Or maybe we should do the work in the trigger component.

**OPTION 1**

We don't add popovertarget, and use the trigger onClick:
- in unsupported browsers, do this once:
  - wake up the popover components via a custom qui-pop-wake event
    - This means the small popover render function runs once for all popovers, nothing else, so it's fine.
    - This moves all popover divs to the bottom of body, our fake qui-top-layer
  - load the polyfill
- in all browsers, once, load the anchor js
- run show() on the popover

client-rendered triggers ensure that the polyfill and anchor are loaded, and don't add onToggle.


**OPTION 2**

- We load the anchor js on document load.
- We render 2 different trigger buttons, one hidden by CSS, depending on support.
- The supported button has popovertarget, the unsupported has an ontoggle that does all the above
- client-rendered triggers render only one button with popovertarget
