### ISSUE TITLE
Finalize the Select

### ISSUE THREAD

**Issue by shairez** [qwikifiers/qwik-ui#517]

**Comment by TheMcnafaha** [comment]
Roadmap, in order of how I want to progress:


- [ ] Make component use visual focus instead of normal focus were the W3 spec says so (affects most of current behavior)

Add missing keyboard support for popup (keys left listed below, listed under the same bullet point is behavior is related)
- [ ] Home & End
- [ ]  Tab & Alt+Up Arrow
- [ ]  PageUp & PageDown
