### ISSUE TITLE
Write tests / infinite looping for the carousel component

### ISSUE THREAD

**Issue by shairez** [qwikifiers/qwik-ui#558]
- [ ] Finish looping
- [ ] Write tests

**Comment by maiieul** [comment]
Has this been implemented @thejackshelton ? If yes can you close pls 🙏

**Comment by thejackshelton** [comment]
> Has this been implemented @thejackshelton ? If yes can you close pls 🙏

It hasn't. But I won't be doing it in the near future, and I don't think we even have this on the sprint, so I'm gonna go ahead and close this for now.

**Comment by shairez** [comment]
@thejackshelton don't you think we'll want to have it in the future?

**Comment by thejackshelton** [comment]
> @thejackshelton don't you think we'll want to have it in the future?

The component needs tests in general, and also some improvements. The ETA on that is not clear.

I will be making a few improvements to the mobile experience based off of what I have already learned (so that it is more usable in its draft state), but cannot justify resources to spend time on testing, new features, and such at the moment.
