### ISSUE TITLE
[🐞] All library components are unacceptable slow

### ISSUE THREAD

**Issue by ziimakc** [qwikifiers/qwik-ui#887]
### Which package is affected?

Headless Kit

### Describe the bug

I assume because of lazy loading library components become painfully slow.

For example clicking on checkbox takes a **second** to react and show a checkbox filled. This kind of behavior is simply unacceptable.

Can we try to load all components on hover by default and add configuration option to preload when in view or in any other way?

### Reproduction

https://qwikui.com/docs/headless/checkbox/

### Steps to reproduce

- Open a page
- Disable cache
- Slowdown internet(optional)
- Hard reload page (F5)
- Click a checkbox

### System Info

```shell
-
```

**Comment by thejackshelton-kunaico** [comment]
Hey @ziimakc!

I went ahead and followed the instructions you mentioned above just to confirm. 

The slow performance you're experiencing is likely due to having cache disabled and a "hard refresh", not because of lazy loading issues. When cache is disabled, every interaction may trigger new network requests, causing noticeable delays.

Qwik's buffering mechanism heavily relies on the service worker prefetching and having those available in the cache, and so a hard refresh or disabled cache option is not a realistic experience of someone visiting your site for the first time.

A more accurate way to test the initial user experience is using an incognito browser with empty cache storage.

![image](https://github.com/user-attachments/assets/49170c1a-1558-4978-9c89-866ff8fffd72)

I do see that the qwik ui site was slower on slow 3g, it took around 2-3 seconds for the checkbox to "click". I tried this on a couple of other similar sites in other frameworks and noticed the average was around 10-15 seconds, with most of the interactions not registering at all 🤔 

Something to also mention, is that the qwik ui site is by no means "optimized". In fact there's actually a bug currently with it executing a bunch more JS than it needs to.  This is specific to the qwik ui site, not Qwik.

Qwik UI is a large monorepo and tracking the cause of the problem has been very obnoxious. What I found was removing any instances of the qwik-themes hook is used seem to "fix" the problem. Any sort of research there is much appreciated.
https://github.com/qwikifiers/qwik-ui/issues/719

https://github.com/user-attachments/assets/902fc774-8f96-44fa-8942-352cab825026

I went ahead and tried it on another Qwik site in chrome's slow 3g and notice it seemed pretty instant to me.  I'm not sure how accurate of a testing tool chrome's slow 3g actually is, and what a better alternative would be.

https://github.com/user-attachments/assets/6751aed6-b65e-4502-9723-7360dbb577f6

Always happy to improve the performance! PR's and research are very welcome 🫶 

My focus has not been on the qwik ui site but more so optimizing the actual components themselves.

**Comment by thejackshelton** [comment]
Hey @ziimakc!

I went ahead and followed the instructions you mentioned above just to confirm. 

The slow performance you're experiencing is likely due to having cache disabled and a "hard refresh", not because of lazy loading issues. When cache is disabled, every interaction may trigger new network requests, causing noticeable delays.

Qwik's buffering mechanism heavily relies on the service worker prefetching and having those available in the cache, and so a hard refresh or disabled cache option is not a realistic experience of someone visiting your site for the first time.

A more accurate way to test the initial user experience is using an incognito browser with empty cache storage.

![image](https://github.com/user-attachments/assets/49170c1a-1558-4978-9c89-866ff8fffd72)

https://github.com/user-attachments/assets/902fc774-8f96-44fa-8942-352cab825026

The above is going to the route without anything in the browser cache on an incognito tab, this does not have any artificial delay.

I do see that the qwik ui site was slower on slow 3g, it took around 2-3 seconds for the checkbox to "click".

Something to also mention, is that the qwik ui site is by no means "optimized". In fact there's actually a bug currently with it executing a bunch more JS than it needs to.  This is specific to the qwik ui site, not Qwik.

Qwik UI is a large monorepo and tracking the cause of the problem has been very obnoxious. What I found was removing any instances of the qwik-themes hook is used seem to "fix" the problem. Any sort of research there is much appreciated.
https://github.com/qwikifiers/qwik-ui/issues/719

https://github.com/user-attachments/assets/6751aed6-b65e-4502-9723-7360dbb577f6

I went ahead and tried it on another Qwik site in chrome's slow 3g and notice it seemed pretty instant to me.  I'm not sure how accurate of a testing tool chrome's slow 3g actually is, and what a better alternative would be.

Always happy to improve the performance! PR's and research are very welcome 🫶 

My focus has not been on the qwik ui site but more so optimizing the actual components themselves.

**Comment by ziimakc** [comment]
@thejackshelton 
Ok, so basically when you load a page first time and click on checkbox - 3 service worker requests are made for a component (visible with slow 3g). If you refresh the page and click on checkbox again - also 3 requests are made, but they are instant because this time we load from browser cache and no delay visible.

What I'm not happy about is this first time user experience with site on slow internet maybe will be slow (if we assume slow3g option mimics bad mobile phone internet somehow), is it possible to make this 3 first requests not on click on checkbox, but at least on hover or even preload all page components in background somehow?

**Comment by maiieul** [comment]
@ziimakc what you're seeing here only happens with "disable cache" + "hard reload". If you use them together, the service worker cache won't be used and all the requests will be done in a waterfall, which means that when you click, the browser will fetch each chunk one by one, which on a slow 3G could take seconds indeed. But that's not what your users will experience.

So this is not your end user experience, but just something that can happen when you dev console is open. As a general rule of thumb, "disable cache" should be enough. See the Qwik docs for more info: https://qwik.dev/docs/advanced/speculative-module-fetching/#misleading-empty-cache-and-hard-reload. 

To see what your users will see:
- open a new incognito navigation window
- open your devtools network tab, slow 3G enabled, no "disable cache" (it'll be like first page load of a user anyways, so things can't be cached yet)
- go to https://qwikui.com/docs/headless/checkbox/
- wait for the page to load entirely (should take a few seconds on slow 3G)
- click on checkbox, it'll be instant.

**Comment by ziimakc** [comment]
@maiieul this is exactly what happens when user visit website first time and this is why I no longer use qwik. You can follow you own steps and try out all components/main menu. Under slow 4g everything takes ~1 second, menu opening takes 4 seconds, this is just unusable.

Problem is not a cache, but a need to load related to action(checkbox click) js chunk and the only wait I see to overcome this - is prefetch all components that's get into view or add an this option to component.

**Comment by maiieul** [comment]
Ah this is another problem. We have qwik insights as a solution to this problem. We should probably integrate it on qwik UI.

**Comment by thejackshelton** [comment]
Hey @ziimakc! I want to update you regarding the prefetching mechanism. This is of course a big priority for the framework, and is something we have been actively improving.

https://5e5b0ab2.qwik-ui-site.pages.dev/docs/headless/introduction/

here is an example deploy without a service worker using the new module preload option. It also does not have any caching. The special sauce is the `rel="modulepreload"`. We're actively looking at this becoming the primary prefetching method in the future.

**Comment by ziimakc** [comment]
@thejackshelton link is not working

**Comment by maiieul** [comment]
@ziimakc thanks for staying in the discussion 😁 

> Under slow 4g everything takes ~1 second, menu opening takes 4 seconds, this is just unusable (cache is enabled, no hard reload).
just for clarification, do things take 1s to 4s right after page load, or even if you wait for all the chunks to be prefetched and cached, and then when you click it still takes 1s to 4s?

**Comment by ziimakc** [comment]
@maiieul even if you wait.

**Comment by maiieul** [comment]
@ziimakc that is not normal. 

Here is what I get on network tab 3G throttling on chrome:
https://github.com/user-attachments/assets/d3e1e7e7-cfea-4a7f-82fb-4405fb83f1e1

As you can see, everything is instant once the page is ready.

Might be the browser you're on or an extension getting in the way maybe 🤔 . Could you share a screen recording of what you see?

**Comment by ziimakc** [comment]
@maiieul I don't have any plugins. It's hard to reproduce as you need to clear chrome disc cache somehow. If you visited qwik-ui once everything already filled it will already be filled. Event in that case any interaction has a slight delay.

What I suggest is try any device or tablet(even without slow3g setting) where qwik-ui were never visited and click around, you see a slight delay on every action and noticeable once on menus,
